name: Setup Moon
description: "This action wraps the official install script to set up the MoonBit toolchain"
author: moonbit-community

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  version:
    description: install MoonBit version (latest|nightly|pre-release; stable->latest, bleeding->nightly)
    required: true
    default: "latest"

runs:
  using: node24
  main: dist/index.js
