name: Setup Moonbit
description: "This action wrap official install script to setup moonbit toolchain"
author: illusory0x0

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  version:
    description: install moonbit version
    required: true
    default: "stable"

runs:
  using: node20
  main: dist/index.js
