name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate-yaml:
    name: Validate YAML files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate action.yml
        uses: ajmyers/yamllint-github-action@v2
        with:
          yaml_file_or_dir: action.yml
          token: ${{ secrets.GITHUB_TOKEN }}
