name: Validate Action Metadata

on:
  pull_request:
  push:

jobs:
  validate-action-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Validate action.yml
        run: npx --yes @action-validator/cli@0.6.0 action.yml
